### ISSUE TITLE
Allow changing loading/fetching tweets notification

### ISSUE THREAD

**Issue by AdminRAT** [ahkohd/vscode-tweet#1]
Sometimes it gets annoying when I'm trying to code and it goes off every 2 minutes. I want to disable it/change the reload interval, but then I can't see new tweets automatically/have to manually refresh it every time. It would be great if there was an option to hide/change those notifications.

**Comment by ahkohd** [comment]
Thanks for raising this. I will work it out in the next patch release this weekend.
1. Disabling Notifications/ Don't disturb mode.

**Comment by ahkohd** [comment]
> Sometimes it gets annoying when I'm trying to code and it goes off every 2 minutes. I want to disable it/change the reload interval, but then I can't see new tweets automatically/have to manually refresh it every time. It would be great if there was an option to hide/change those notifications.

Thanks for your feedback. I have implemented the **Don't Disturb Feature**. 
Update your VS CODE TWEET (v0.13.0) and enable don't disturb in the vscode tweet settings.

```
Open Vscode Tweet Settings > Search For dontdisturb > Check the box to enable this feature.
```
